#!/usr/bin/env node
import meow from 'meow';
// import unicornFun from 'unicorn-fun';
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url';
import { openFile } from './crossPlatformFileOpener.js';

const cli = meow(`
	Usage
		$ journal
		$ journal <title>
	Options
		--template  Which template to use. Only one now  [Default: memo]
		--dir		Setup journal directory
	Examples
		$ journal --dir ./my/desired/journal/directory
			Setup your journal to target this folder
		$ journal
			creates a new journal entry, tagged today.
		$ journal This is my journal title entry
			creates a new journal entry, tagged today, with the provided written title.
		$ journal --template=memo Todays Title
			creates a new journal entry from template name memo
`, {
	// input: ['setup', 'new'],
	importMeta: import.meta,
	flags: {
		dir: {
			type: 'string',
			alias: 'd'
		},
		template: {
			type: 'string',
			alias: 't',
			default: 'memo'
		}
	}
});
console.log('cli.flags.template',cli.flags.template)
const randomAwesomeShorts = [
	"Ran a marathon",
	"Had dinner with family",
	"Hiked a mountain",
]
function journalTemplate(currentDate, title = ""){
	const currentDateString = currentDate.toDateString()
	return `Journal - ${currentDateString}
# Short
	${title || randomAwesomeShorts[Math.round(Math.random() * randomAwesomeShorts.length)]}
# Long
	...

Generated by Journal.cli
`
}
function getJournalSettingsPath(){
	return path.join(__dirname, 'journal.settings')
}
function getJournalPath(){
	const settingsPath = getJournalSettingsPath()
	if(!fs.existsSync(settingsPath)){
		return ""
	}
	return fs.readFileSync(settingsPath).toString()
}
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function process(){
	if(cli.flags.dir){
		const journalPath = cli.flags.dir
		if(!journalPath){
			console.log('Please provide a valid path')
			return
		}
		let absoluteJournalPath = journalPath
		if(!fs.existsSync(journalPath)){
			absoluteJournalPath = fileURLToPath(path.join(process.cwd(), journalPath))
		} else {
			absoluteJournalPath = fs.realpathSync(absoluteJournalPath)
		}
		fs.writeFileSync(getJournalSettingsPath(), absoluteJournalPath)
		console.log('Journal location saved to', absoluteJournalPath)
	} else {
		const journalDirectory = getJournalPath()
		if(!journalDirectory || !fs.existsSync(journalDirectory)) {
			console.log('Journal directory not available. Setup with `journal setup <path>`')
			return
		}
		const title = cli?.input?.join(' ') || ''
		const currentDate = new Date()
		const template = journalTemplate(currentDate, title)
		const journalEntryPath = path.join(journalDirectory, `journal-${currentDate.toDateString().split(' ').join('-')}.md`)
		fs.writeFileSync(journalEntryPath, template)
		openFile(journalEntryPath)
		console.log('Journal set created at', journalEntryPath)
	}
}
process()
