import Handlebars from 'handlebars'
import path from 'path'
import { FileSystem } from './FileSystem'
import { JourError } from './JourError'
import { JourSystem } from './JourSystem'

const randomAwesomeShorts = [
	"Ran a marathon",
	"Had dinner with family",
	"Hiked a mountain",
]
export function jourTemplate(js: JourSystem, title = "") {
	const currentDateString = js.config.currentTime.toLocaleDateString(js.config.locale)
	const jourTemplateData: TemplateData = {
		entryTitle: 'Jour cli',
		date: js.config.currentTime,
		currentDateString: currentDateString,
		title: title || randomAwesomeShorts[Math.round(Math.random() * randomAwesomeShorts.length)],
		details: "",
		footer: "Generated by Jour cli",
	}

	return Template.processTemplateName(js, js.config.template, jourTemplateData)
}
export class TemplateData {
	entryTitle = 'Jour cli'
	date: Date = new Date()
	currentDateString: string = this.date.toDateString()
	title = "Title"
	details = "Details"
	footer = "Generated by Jour cli"
}

export class Template {
	static processTemplateName(js: JourSystem, templateName = "memo", templateData: TemplateData): string {
		// Dirty code
		js.LOG.debug('__dirname', __dirname)
		const templateFilePath = Template.toPath(templateName)
		js.LOG.debug('templateFilePath', templateFilePath)
		if (Template.isValidTemplateLocation(templateFilePath)){
			const templateFile = FileSystem.readFile(templateFilePath)
			if(Template.isValidTemplate(templateFile)){
				const template = Handlebars.compile(templateFile)
				return template({jour: templateData, extra: {}})
			} else {
				throw new JourError("Invalid template")
			}
		} else {
			throw new JourError('Template file not found. Set it with `jour --template-path <path-to-template-folder>`')
		}
	}
	static isValidTemplate(templateString: string){
		try {
			Handlebars.precompile(templateString)
			return true
		} catch (error) {
			return false
		}
	}
	static isValidTemplateLocation(templateNameOrPath: string) {
		return FileSystem.isFile(templateNameOrPath)
		|| FileSystem.isFile(path.join(__dirname, '..', 'templates', templateNameOrPath + '.hbs'))
	}
	static toPath(templateNameOrPath: string) {
		if(FileSystem.isFile(templateNameOrPath)){
			return templateNameOrPath
		} else {
			return path.join(__dirname, '..', 'templates', templateNameOrPath + '.hbs')
		}
	}
}
