import Handlebars from 'handlebars'
import fs from 'fs'
import path from 'path'
import { FileSystem } from './FileSystem'

const randomAwesomeShorts = [
	"Ran a marathon",
	"Had dinner with family",
	"Hiked a mountain",
]
export function journalTemplate(currentDate: Date, title = "") {
	const currentDateString = currentDate.toDateString()
	const journalTemplateData: TemplateData = {
		entryTitle: 'Journal',
		date: currentDate,
		currentDateString: currentDateString,
		title: title || randomAwesomeShorts[Math.round(Math.random() * randomAwesomeShorts.length)],
		details: "",
		footer: "Generated by Journal.cli",
	}
	return Template.processTemplateName('memo', journalTemplateData)
}
export class TemplateData {
	entryTitle = 'Journal'
	date: Date = new Date()
	currentDateString: string = this.date.toDateString()
	title = "Title"
	details = "Details"
	footer = "Generated by Journal.cli"
}

export class Template {
	static processTemplateName(templateName = "memo", templateData: TemplateData): string {
		// Dirty code
		console.log('__dirname', __dirname)
		const templateFilePath = Template.toPath(templateName)
		console.log('templateFilePath', templateFilePath)
		if (Template.isValidTemplateLocation(templateFilePath)){
			const templateFile = FileSystem.readFile(templateFilePath)
			if(Template.isValidTemplate(templateFile)){
				const template = Handlebars.compile(templateFile)
				return template({journal: templateData, extra: {}})
			} else {
				console.log("Invalid template")
			}
		} else {
			console.log('Template file not found. Set it with `journal --template-path <path-to-template-folder>`')
			return ""
		}
	}
	static isValidTemplate(templateString: string){
		try {
			Handlebars.precompile(templateString)
			return true
		} catch (error) {
			return false
		}
	}
	static isValidTemplateLocation(templateNameOrPath: string) {
		return FileSystem.isFile(templateNameOrPath)
		|| FileSystem.isFile(path.join(__dirname, '..', 'templates', templateNameOrPath + '.hbs'))
	}
	static toPath(templateNameOrPath: string) {
		if(FileSystem.isFile(templateNameOrPath)){
			return templateNameOrPath
		} else {
			return path.join(__dirname, '..', 'templates', templateNameOrPath + '.hbs')
		}
	}
}
