import Handlebars from 'handlebars'
import fs from 'fs'
import path from 'path'

export class TemplateData {
	entryTitle = 'Journal'
	date: Date = new Date()
	currentDateString: string = this.date.toDateString()
	title = "Title"
	long = "Long"
	footer = "Generated by Journal.cli"
}
// const __filename = fileURLToPath(import.meta.url);
// const __dirname = path.dirname(__filename);
export class Template {
	static processTemplateName(templateName = "memo", templateData: TemplateData): string {
		console.log('__dirname', __dirname)
		const templateFilePath = path.join(__dirname, '..', 'templates', templateName + '.hbs')
		console.log('templateFilePath', templateFilePath)
		if(fs.existsSync(templateFilePath)){
			const templateFile = fs.readFileSync(templateFilePath).toString()
			const template =  Handlebars.compile(templateFile)
			return template(templateData)
		} else {
			console.log('Template file not found. Set it with `journal --template-path <path-to-template-folder>`')
			return ""
		}
	}
}
