name: Release, publish to NPM
on:
  push:
    branches:
      - main
jobs:
  release:
    name: NPM publish ${{ matrix.node-version }}
    if: github.actor != 'github'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: npm run patch-release
